# Generated by Django 4.1.7 on 2023-03-08 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_in', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CopyLoan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('returned', models.BooleanField(default=False)),
                ('returned_in', models.DateTimeField()),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies_loan', to='copies.copy')),
            ],
        ),
    ]
