# Generated by Django 4.1.7 on 2023-03-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copies', '0003_copy_disponibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyloan',
            name='returned_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
